import{plant} from './app/shared/models/plant';
//import { Tag } from './app/shared/models/Tag';
export const sample_plants: plant[] = [
  {
    id:'1',
    name: 'spider plant',
   // cookTime: '10-20',
    price: 10,
    favorite: false,
    //origins: ['italy'],
    //stars: 4.5,
    imageUrl: 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1629245918-51w2is3YV4L._SL500_.jpg?crop=1xw:1.00xh;center,top&resize=768:*',
    description: "The recipe for a happy yucca is easy: sun, sun and more sun. Plant in a container deep enough to balance the top-heavy woody stems and water sparingly. Take note: This plant is toxic to cats and dogs.",
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Mini Jade Plant',
    price: 20,
   // cookTime: '20-30',
    favorite: true,
   // origins: ['persia', 'middle east', 'china'],
    //stars: 4.7,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0253/6701/9565/products/Philodendron-Pink-Princess-Grow-Pot-Small_816774d6-4dcb-4c5d-a147-05c1025a9cc4_600x600.jpg?v=1649363100',
    description: "The recipe for a happy yucca is easy: sun, sun and more sun. Plant in a container deep enough to balance the top-heavy woody stems and water sparingly. Take note: This plant is toxic to cats and dogs.",
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Money Tree',
    price: 5,
   // cookTime: '10-15',
    favorite: false,
   // origins: ['germany', 'us'],
    //stars: 3.5,
    imageUrl: 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1658931779-51RJ3e6NEdL._SL500_.jpg?crop=1.00xw:0.752xh;0,0.248xh&resize=768:*',
    description: "The recipe for a happy yucca is easy: sun, sun and more sun. Plant in a container deep enough to balance the top-heavy woody stems and water sparingly. Take note: This plant is toxic to cats and dogs.",
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Asoaragus Fern',
    price: 2,
    //cookTime: '15-20',
    favorite: true,
   // origins: ['belgium', 'france'],
   // stars: 3.3,
    imageUrl: 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1554477330-beautiful-asparagus-fern-plant-in-a-basket-royalty-free-image-972247932-1546889240.jpg?crop=0.457xw:0.301xh;0.447xw,0.372xh&resize=768:*',
    description: "The recipe for a happy yucca is easy: sun, sun and more sun. Plant in a container deep enough to balance the top-heavy woody stems and water sparingly. Take note: This plant is toxic to cats and dogs.",
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Dragon Tree',
    price: 11,
   // cookTime: '40-50',
    favorite: false,
    //origins: ['india', 'asia'],
   // stars: 3.0,
    imageUrl: 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1557255687-flowers-in-a-pot-indoors-royalty-free-image-940610580-1557255594.jpg?crop=0.559xw:0.839xh;0,0.142xh&resize=768:*',
    description: "The recipe for a happy yucca is easy: sun, sun and more sun. Plant in a container deep enough to balance the top-heavy woody stems and water sparingly. Take note: This plant is toxic to cats and dogs.",
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'ZZ Plant',
    price: 9,
   // cookTime: '40-50',
    favorite: false,
   // origins: ['italy'],
   // stars: 4.0,
    imageUrl: 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1660073901-best-indoor-plants-zz-plant-1660073875.png?crop=1.00xw:0.802xh;0,0.168xh&resize=768:*',
    description: "The recipe for a happy yucca is easy: sun, sun and more sun. Plant in a container deep enough to balance the top-heavy woody stems and water sparingly. Take note: This plant is toxic to cats and dogs.",
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

/*export const sample_tags:Tag[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]*/
